---

- name: Importing APT key
  apt_key:
    id: "{{ nginx_repo_key }}"
    keyserver: keyserver.ubuntu.com
    state: present

- name: Adding APT repository
  apt_repository:
    repo: "{{ nginx_repo }}"
    update_cache: yes

- name: Installing packages
  package:
    name: "{{ nginx_package }}"
    state: present
