---

- import_tasks: install.yml
  tags:
    - web
    - nginx
    - install
    - nginx-install

- import_tasks: config.yml
  tags:
    - web
    - nginx
    - config
    - nginx-config

- import_tasks: manage.yml
  when: nginx_sites | length
  tags:
    - web
    - nginx
    - manage
    - nginx-manage

- import_tasks: proxies.yml
  when: nginx_proxies | length
  tags:
    - web
    - nginx
    - manage
    - nginx-manage
    - proxies

- import_tasks: service.yml
  tags:
    - web
    - nginx
    - service
    - nginx-service
