---

- name: Configuring proxies
  template:
    src: "{{ item.template|default('etc/nginx/sites-available/proxy.j2') }}"
    dest: "/etc/nginx/sites-available/{{ item.id }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ nginx_proxies }}"
  notify: reload nginx

- name: Enabling proxies
  file:
    src: "/etc/nginx/sites-available/{{ item.id }}"
    dest: "/etc/nginx/sites-enabled/{{ item.id }}"
    state: link
  when: item.state is not defined or item.state == 'present'
  with_items: "{{ nginx_proxies }}"
  notify: reload nginx

- name: Disabling proxies
  file:
    src: "/etc/nginx/sites-available/{{ item.id }}"
    dest: "/etc/nginx/sites-enabled/{{ item.id }}"
    state: absent
  when: item.state is defined and item.state == 'absent'
  with_items: "{{ nginx_proxies }}"
  notify: restart nginx

